name: Build Application Binaries

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      
      - name: Make Gradle wrapper executable (Linux/macOS)
        if: runner.os != 'Windows'
        run: chmod +x ./gradlew
      
      - name: Build with Gradle
        run: ./gradlew composeApp:packageDistributionForCurrentOS
      
      - name: Upload Windows MSI
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v3
        with:
          name: windows-msi
          path: composeApp/build/compose/binaries/main/msi/*.msi
          if-no-files-found: error
      
      - name: Upload macOS DMG
        if: runner.os == 'macOS'
        uses: actions/upload-artifact@v3
        with:
          name: macos-dmg
          path: composeApp/build/compose/binaries/main/dmg/*.dmg
          if-no-files-found: error
      
      - name: Upload Linux DEB
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v3
        with:
          name: linux-deb
          path: composeApp/build/compose/binaries/main/deb/*.deb
          if-no-files-found: error